// Auto-generated by the build system – do not edit manually.
export const APP_NAME = '@jeansoft/cocos-icon-gen';
export const APP_VERSION = '0.1.0';
export const APP_DESCRIPTION =
  'Generate iOS, macOS, and Windows app icons for Cocos Creator projects from a single source image';
